const SUPABASE_URL='https://xvyzwrkkvvpoqwlanaas.supabase.co';
const SUPABASE_KEY='sb_publishable_q08Iv5vIYTIhvs-IwSQcNg_6xXwFNbF';
const OWNER_EMAIL='nishagolden50@gmail.com';
const client=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let inventory=[],sales=[],expenses=[],user=null;
const money=n=>'KES '+Number(n||0).toLocaleString('en-KE',{maximumFractionDigits:2}),fmt=d=>new Date(d).toLocaleString('en-KE',{dateStyle:'medium',timeStyle:'short'}),today=d=>new Date(d).toDateString()===new Date().toDateString();
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2500)}
async function start(){const {data}=await client.auth.getSession();showSession(data.session);client.auth.onAuthStateChange((_e,s)=>showSession(s))}
function showSession(session){user=session?.user||null;$('#auth').classList.toggle('hidden',!!user);$('#app').classList.toggle('hidden',!user);if(user){$('#user-email').textContent=user.email;loadAll()}}
$('#login-form').onsubmit=async e=>{e.preventDefault();$('#auth-error').textContent='';const {error}=await client.auth.signInWithPassword({email:OWNER_EMAIL,password:$('#password').value});if(error)$('#auth-error').textContent=error.message};$('#logout').onclick=()=>client.auth.signOut();
async function loadAll(){const [a,b,c]=await Promise.all([client.from('fruit_inventory').select('*').order('name'),client.from('fruit_sales').select('*').order('created_at',{ascending:false}),client.from('business_expenses').select('*').order('created_at',{ascending:false})]);const err=a.error||b.error||c.error;if(err){toast('Setup required: run setup.sql in Supabase');return}inventory=a.data;sales=b.data;expenses=c.data;render()}
function render(){renderDashboard();renderInventory();renderSales();renderExpenses()}
function renderDashboard(){const ts=sales.filter(x=>today(x.created_at)),te=expenses.filter(x=>today(x.created_at)),revenue=ts.reduce((a,x)=>a+x.quantity*x.unit_price,0),cogs=ts.reduce((a,x)=>a+x.quantity*x.unit_cost,0),costs=te.reduce((a,x)=>a+x.amount,0);$('#today').textContent=new Date().toLocaleDateString('en-KE',{day:'numeric',month:'short',year:'numeric'});$('#today-sales').textContent=money(revenue);$('#today-profit').textContent=money(revenue-cogs-costs);$('#today-count').textContent=ts.length;$('#stock-value').textContent=money(inventory.reduce((a,x)=>a+x.quantity*x.cost_price,0));$('#today-expenses').textContent=money(costs);$('#mpesa-total').textContent=money(ts.filter(x=>x.payment_method==='M-Pesa').reduce((a,x)=>a+x.quantity*x.unit_price,0));$('#low-count').textContent=inventory.filter(x=>x.quantity<=x.low_stock_level).length;$('#dash-stock').innerHTML=inventory.slice(0,5).map(x=>row(x.name,`${x.quantity} ${x.unit} · ${money(x.selling_price)} each`,x.quantity<=x.low_stock_level?'Low stock':'In stock')).join('')||empty('No fruits yet')}
const row=(title,meta,right,buttons='')=>`<div class="row"><div><strong>${escapeHtml(title)}</strong><small>${escapeHtml(meta)}</small></div><div class="money">${escapeHtml(right)}<div class="actions">${buttons}</div></div></div>`,empty=t=>`<div class="empty">${t}</div>`,escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderInventory(){$('#inventory-list').innerHTML=inventory.map(x=>row(x.name,`${x.quantity} ${x.unit} · Cost ${money(x.cost_price)} · Sell ${money(x.selling_price)}`,x.quantity<=x.low_stock_level?'Low stock':'Available',`<button class="mini" onclick="editProduct('${x.id}')">Edit</button>`)).join('')||empty('Add your first fruit product')}
function renderSales(){$('#sales-list').innerHTML=sales.map(x=>row(`${x.product_name} × ${x.quantity}`,`${fmt(x.created_at)} · ${x.payment_method}${x.mpesa_code?' · '+x.mpesa_code:''}`,money(x.quantity*x.unit_price),`<button class="mini" onclick="editSale('${x.id}')">Edit</button>`)).join('')||empty('No sales recorded yet')}
function renderExpenses(){$('#expenses-list').innerHTML=expenses.map(x=>row(x.category,`${fmt(x.created_at)}${x.note?' · '+x.note:''}`,'− '+money(x.amount),`<button class="mini" onclick="editExpense('${x.id}')">Edit</button>`)).join('')||empty('No expenses recorded yet')}
$$('nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));function navigate(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo({top:0,behavior:'smooth'})}
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#new-product').onclick=()=>openProduct();$('#new-sale').onclick=()=>openSale();$('#new-expense').onclick=()=>openExpense();
function openProduct(x){$('#product-form').reset();$('#product-id').value=x?.id||'';$('#product-title').textContent=x?'Edit fruit':'Add fruit';$('#product-name').value=x?.name||'';$('#product-qty').value=x?.quantity??'';$('#product-unit').value=x?.unit||'pieces';$('#product-cost').value=x?.cost_price??'';$('#product-price').value=x?.selling_price??'';$('#product-low').value=x?.low_stock_level??10;$('#product-dialog').showModal()}window.editProduct=id=>openProduct(inventory.find(x=>x.id===id));
$('#product-form').onsubmit=async e=>{e.preventDefault();const id=$('#product-id').value,p={name:$('#product-name').value.trim(),quantity:+$('#product-qty').value,unit:$('#product-unit').value,cost_price:+$('#product-cost').value,selling_price:+$('#product-price').value,low_stock_level:+$('#product-low').value,user_id:user.id};const q=id?client.from('fruit_inventory').update(p).eq('id',id):client.from('fruit_inventory').insert(p);const {error}=await q;if(error)return toast(error.message);$('#product-dialog').close();toast('Fruit inventory saved');loadAll()};
function saleOptions(value){$('#sale-product').innerHTML=inventory.map(x=>`<option value="${x.id}" ${x.id===value?'selected':''}>${escapeHtml(x.name)} — ${x.quantity} ${escapeHtml(x.unit)}</option>`).join('')}function openSale(s){$('#sale-form').reset();saleOptions(s?.product_id);$('#sale-id').value=s?.id||'';$('#sale-title').textContent=s?'Edit sale':'Record sale';$('#sale-qty').value=s?.quantity??1;const p=inventory.find(x=>x.id===$('#sale-product').value);$('#sale-price').value=s?.unit_price??p?.selling_price??0;$('#sale-payment').value=s?.payment_method||'M-Pesa';$('#sale-code').value=s?.mpesa_code||'';$('#void-sale').classList.toggle('hidden',!s);$('#sale-dialog').showModal()}window.editSale=id=>openSale(sales.find(x=>x.id===id));$('#sale-product').onchange=()=>{const p=inventory.find(x=>x.id===$('#sale-product').value);if(p)$('#sale-price').value=p.selling_price};
$('#sale-form').onsubmit=async e=>{e.preventDefault();const id=$('#sale-id').value,p=inventory.find(x=>x.id===$('#sale-product').value),qty=+$('#sale-qty').value;if(!p)return toast('Add fruit inventory first');const old=id?sales.find(x=>x.id===id):null,available=p.quantity+(old?.product_id===p.id?old.quantity:0);if(qty>available)return toast(`Only ${available} ${p.unit} available`);if(old){const oldP=inventory.find(x=>x.id===old.product_id);if(oldP)await client.from('fruit_inventory').update({quantity:oldP.quantity+old.quantity}).eq('id',oldP.id)}const sale={product_id:p.id,product_name:p.name,quantity:qty,unit_price:+$('#sale-price').value,unit_cost:p.cost_price,payment_method:$('#sale-payment').value,mpesa_code:$('#sale-code').value.trim()||null,user_id:user.id};const {error}=id?await client.from('fruit_sales').update(sale).eq('id',id):await client.from('fruit_sales').insert(sale);if(error)return toast(error.message);await client.from('fruit_inventory').update({quantity:available-qty}).eq('id',p.id);$('#sale-dialog').close();toast(id?'Sale updated':'Sale recorded');loadAll()};
$('#void-sale').onclick=async()=>{const id=$('#sale-id').value,s=sales.find(x=>x.id===id);if(!s||!confirm('Void sale and restore its stock?'))return;const p=inventory.find(x=>x.id===s.product_id);if(p)await client.from('fruit_inventory').update({quantity:p.quantity+s.quantity}).eq('id',p.id);const {error}=await client.from('fruit_sales').delete().eq('id',id);if(error)return toast(error.message);$('#sale-dialog').close();toast('Sale voided and stock restored');loadAll()};
function openExpense(x){$('#expense-form').reset();$('#expense-id').value=x?.id||'';$('#expense-title').textContent=x?'Edit expense':'Add expense';$('#expense-category').value=x?.category||'Transport';$('#expense-amount').value=x?.amount??'';$('#expense-note').value=x?.note||'';$('#expense-dialog').showModal()}window.editExpense=id=>openExpense(expenses.find(x=>x.id===id));$('#expense-form').onsubmit=async e=>{e.preventDefault();const id=$('#expense-id').value,p={category:$('#expense-category').value,amount:+$('#expense-amount').value,note:$('#expense-note').value.trim()||null,user_id:user.id};const {error}=id?await client.from('business_expenses').update(p).eq('id',id):await client.from('business_expenses').insert(p);if(error)return toast(error.message);$('#expense-dialog').close();toast('Expense saved');loadAll()};start();
